//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gw2LogParser.Properties {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gw2LogParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string actors {
            get { return ResourceManager.GetString("actors", resourceCulture); }
        }

        public static string animator {
            get { return ResourceManager.GetString("animator", resourceCulture); }
        }

        public static string compressionUtils {
            get { return ResourceManager.GetString("compressionUtils", resourceCulture); }
        }

        public static string css {
            get { return ResourceManager.GetString("css", resourceCulture); }
        }

        public static string decorations {
            get { return ResourceManager.GetString("decorations", resourceCulture); }
        }

        public static string functions {
            get { return ResourceManager.GetString("functions", resourceCulture); }
        }

        public static string global {
            get { return ResourceManager.GetString("global", resourceCulture); }
        }

        public static string healingExtFunctions {
            get { return ResourceManager.GetString("healingExtFunctions", resourceCulture); }
        }

        public static string healingExtGlobals {
            get { return ResourceManager.GetString("healingExtGlobals", resourceCulture); }
        }

        public static string main_js {
            get { return ResourceManager.GetString("main_js", resourceCulture); }
        }

        public static string mixins {
            get { return ResourceManager.GetString("mixins", resourceCulture); }
        }

        public static string player_summary {
            get { return ResourceManager.GetString("player_summary", resourceCulture); }
        }

        public static string template_html {
            get { return ResourceManager.GetString("template_html", resourceCulture); }
        }

        public static string tmplAdvancedRotation {
            get { return ResourceManager.GetString("tmplAdvancedRotation", resourceCulture); }
        }

        public static string tmplBarrierDistPlayer {
            get { return ResourceManager.GetString("tmplBarrierDistPlayer", resourceCulture); }
        }

        public static string tmplBarrierDistTable {
            get { return ResourceManager.GetString("tmplBarrierDistTable", resourceCulture); }
        }

        public static string tmplBarrierTakenDistPlayer {
            get { return ResourceManager.GetString("tmplBarrierTakenDistPlayer", resourceCulture); }
        }

        public static string tmplBuffStats {
            get { return ResourceManager.GetString("tmplBuffStats", resourceCulture); }
        }

        public static string tmplBuffStatsPlayer {
            get { return ResourceManager.GetString("tmplBuffStatsPlayer", resourceCulture); }
        }

        public static string tmplBuffStatsTarget {
            get { return ResourceManager.GetString("tmplBuffStatsTarget", resourceCulture); }
        }

        public static string tmplBuffTab {
            get { return ResourceManager.GetString("tmplBuffTab", resourceCulture); }
        }

        public static string tmplBuffTable {
            get { return ResourceManager.GetString("tmplBuffTable", resourceCulture); }
        }

        public static string tmplBuffTables {
            get { return ResourceManager.GetString("tmplBuffTables", resourceCulture); }
        }

        public static string tmplBuffVolumeStats {
            get { return ResourceManager.GetString("tmplBuffVolumeStats", resourceCulture); }
        }

        public static string tmplBuffVolumeStatsPlayer {
            get { return ResourceManager.GetString("tmplBuffVolumeStatsPlayer", resourceCulture); }
        }

        public static string tmplBuffVolumeStatsTarget {
            get { return ResourceManager.GetString("tmplBuffVolumeStatsTarget", resourceCulture); }
        }

        public static string tmplBuffVolumeTable {
            get { return ResourceManager.GetString("tmplBuffVolumeTable", resourceCulture); }
        }

        public static string tmplBuffVolumeTables {
            get { return ResourceManager.GetString("tmplBuffVolumeTables", resourceCulture); }
        }

        public static string tmplCombatReplayActorBuffStats {
            get { return ResourceManager.GetString("tmplCombatReplayActorBuffStats", resourceCulture); }
        }

        public static string tmplCombatReplayActorRotation {
            get { return ResourceManager.GetString("tmplCombatReplayActorRotation", resourceCulture); }
        }

        public static string tmplCombatReplayActorsStats {
            get { return ResourceManager.GetString("tmplCombatReplayActorsStats", resourceCulture); }
        }

        public static string tmplCombatReplayAnimationControl {
            get { return ResourceManager.GetString("tmplCombatReplayAnimationControl", resourceCulture); }
        }

        public static string tmplCombatReplayDamageData {
            get { return ResourceManager.GetString("tmplCombatReplayDamageData", resourceCulture); }
        }

        public static string tmplCombatReplayDamageTable {
            get { return ResourceManager.GetString("tmplCombatReplayDamageTable", resourceCulture); }
        }

        public static string tmplCombatReplayExtraDecorations {
            get { return ResourceManager.GetString("tmplCombatReplayExtraDecorations", resourceCulture); }
        }

        public static string tmplCombatReplayMechanicsList {
            get { return ResourceManager.GetString("tmplCombatReplayMechanicsList", resourceCulture); }
        }

        public static string tmplCombatReplayPlayerStats {
            get { return ResourceManager.GetString("tmplCombatReplayPlayerStats", resourceCulture); }
        }

        public static string tmplCombatReplayPlayerStatus {
            get { return ResourceManager.GetString("tmplCombatReplayPlayerStatus", resourceCulture); }
        }

        public static string tmplCombatReplayStatusData {
            get { return ResourceManager.GetString("tmplCombatReplayStatusData", resourceCulture); }
        }

        public static string tmplCombatReplayTargetStats {
            get { return ResourceManager.GetString("tmplCombatReplayTargetStats", resourceCulture); }
        }

        public static string tmplCombatReplayTargetStatus {
            get { return ResourceManager.GetString("tmplCombatReplayTargetStatus", resourceCulture); }
        }

        public static string tmplCombatReplayUI {
            get { return ResourceManager.GetString("tmplCombatReplayUI", resourceCulture); }
        }

        public static string tmplConditionsTable {
            get { return ResourceManager.GetString("tmplConditionsTable", resourceCulture); }
        }

        public static string tmplConditionsVolumeTable {
            get { return ResourceManager.GetString("tmplConditionsVolumeTable", resourceCulture); }
        }

        public static string tmplDamageDistPlayer {
            get { return ResourceManager.GetString("tmplDamageDistPlayer", resourceCulture); }
        }

        public static string tmplDamageDistTable {
            get { return ResourceManager.GetString("tmplDamageDistTable", resourceCulture); }
        }

        public static string tmplDamageDistTarget {
            get { return ResourceManager.GetString("tmplDamageDistTarget", resourceCulture); }
        }

        public static string tmplDamageModifierPersStats {
            get { return ResourceManager.GetString("tmplDamageModifierPersStats", resourceCulture); }
        }

        public static string tmplDamageModifierStats {
            get { return ResourceManager.GetString("tmplDamageModifierStats", resourceCulture); }
        }

        public static string tmplDamageModifierStatsContainer {
            get { return ResourceManager.GetString("tmplDamageModifierStatsContainer", resourceCulture); }
        }

        public static string tmplDamageModifierTable {
            get { return ResourceManager.GetString("tmplDamageModifierTable", resourceCulture); }
        }

        public static string tmplDamageTable {
            get { return ResourceManager.GetString("tmplDamageTable", resourceCulture); }
        }

        public static string tmplDamageTakenDistPlayer {
            get { return ResourceManager.GetString("tmplDamageTakenDistPlayer", resourceCulture); }
        }

        public static string tmplDamageTakenDistTarget {
            get { return ResourceManager.GetString("tmplDamageTakenDistTarget", resourceCulture); }
        }

        public static string tmplDeathRecap {
            get { return ResourceManager.GetString("tmplDeathRecap", resourceCulture); }
        }

        public static string tmplDebuffTable {
            get { return ResourceManager.GetString("tmplDebuffTable", resourceCulture); }
        }

        public static string tmplDebuffVolumeTable {
            get { return ResourceManager.GetString("tmplDebuffVolumeTable", resourceCulture); }
        }

        public static string tmplDefenseTable {
            get { return ResourceManager.GetString("tmplDefenseTable", resourceCulture); }
        }

        public static string tmplDPSGraph {
            get { return ResourceManager.GetString("tmplDPSGraph", resourceCulture); }
        }

        public static string tmplDPSGraphModeSelector {
            get { return ResourceManager.GetString("tmplDPSGraphModeSelector", resourceCulture); }
        }

        public static string tmplEncounter {
            get { return ResourceManager.GetString("tmplEncounter", resourceCulture); }
        }

        public static string tmplEnhancementBuffTable {
            get { return ResourceManager.GetString("tmplEnhancementBuffTable", resourceCulture); }
        }

        public static string tmplFood {
            get { return ResourceManager.GetString("tmplFood", resourceCulture); }
        }

        public static string tmplGameplayTable {
            get { return ResourceManager.GetString("tmplGameplayTable", resourceCulture); }
        }

        public static string tmplGearBuffTable {
            get { return ResourceManager.GetString("tmplGearBuffTable", resourceCulture); }
        }

        public static string tmplGearBuffVolumeTable {
            get { return ResourceManager.GetString("tmplGearBuffVolumeTable", resourceCulture); }
        }

        public static string tmplGraph {
            get { return ResourceManager.GetString("tmplGraph", resourceCulture); }
        }

        public static string tmplGraphStats {
            get { return ResourceManager.GetString("tmplGraphStats", resourceCulture); }
        }

        public static string tmplHealingDistPlayer {
            get { return ResourceManager.GetString("tmplHealingDistPlayer", resourceCulture); }
        }

        public static string tmplHealingDistTable {
            get { return ResourceManager.GetString("tmplHealingDistTable", resourceCulture); }
        }

        public static string tmplHealingExtensionView {
            get { return ResourceManager.GetString("tmplHealingExtensionView", resourceCulture); }
        }

        public static string tmplHealingGraphStats {
            get { return ResourceManager.GetString("tmplHealingGraphStats", resourceCulture); }
        }

        public static string tmplHealingStatTables {
            get { return ResourceManager.GetString("tmplHealingStatTables", resourceCulture); }
        }

        public static string tmplHealingTakenDistPlayer {
            get { return ResourceManager.GetString("tmplHealingTakenDistPlayer", resourceCulture); }
        }

        public static string tmplHPSGraph {
            get { return ResourceManager.GetString("tmplHPSGraph", resourceCulture); }
        }

        public static string tmplHPSGraphModeSelector {
            get { return ResourceManager.GetString("tmplHPSGraphModeSelector", resourceCulture); }
        }

        public static string tmplIncomingHealingTable {
            get { return ResourceManager.GetString("tmplIncomingHealingTable", resourceCulture); }
        }

        public static string tmplMain {
            get { return ResourceManager.GetString("tmplMain", resourceCulture); }
        }

        public static string tmplMainView {
            get { return ResourceManager.GetString("tmplMainView", resourceCulture); }
        }

        public static string tmplMechanicsStats {
            get { return ResourceManager.GetString("tmplMechanicsStats", resourceCulture); }
        }

        public static string tmplMechanicsTable {
            get { return ResourceManager.GetString("tmplMechanicsTable", resourceCulture); }
        }

        public static string tmplNourishmentBuffTable {
            get { return ResourceManager.GetString("tmplNourishmentBuffTable", resourceCulture); }
        }

        public static string tmplOffensiveTable {
            get { return ResourceManager.GetString("tmplOffensiveTable", resourceCulture); }
        }

        public static string tmplOtherConsumableBuffTable {
            get { return ResourceManager.GetString("tmplOtherConsumableBuffTable", resourceCulture); }
        }

        public static string tmplOutgoingHealingTable {
            get { return ResourceManager.GetString("tmplOutgoingHealingTable", resourceCulture); }
        }

        public static string tmplPersonalBuffTable {
            get { return ResourceManager.GetString("tmplPersonalBuffTable", resourceCulture); }
        }

        public static string tmplPersonalBuffVolumeTable {
            get { return ResourceManager.GetString("tmplPersonalBuffVolumeTable", resourceCulture); }
        }

        public static string tmplPhase {
            get { return ResourceManager.GetString("tmplPhase", resourceCulture); }
        }

        public static string tmplPlayerBuffTab {
            get { return ResourceManager.GetString("tmplPlayerBuffTab", resourceCulture); }
        }

        public static string tmplPlayerHealingStats {
            get { return ResourceManager.GetString("tmplPlayerHealingStats", resourceCulture); }
        }

        public static string tmplPlayerHealingTab {
            get { return ResourceManager.GetString("tmplPlayerHealingTab", resourceCulture); }
        }

        public static string tmplPlayerHealingTabGraph {
            get { return ResourceManager.GetString("tmplPlayerHealingTabGraph", resourceCulture); }
        }

        public static string tmplPlayers {
            get { return ResourceManager.GetString("tmplPlayers", resourceCulture); }
        }

        public static string tmplPlayersRotation {
            get { return ResourceManager.GetString("tmplPlayersRotation", resourceCulture); }
        }

        public static string tmplPlayersRotationTab {
            get { return ResourceManager.GetString("tmplPlayersRotationTab", resourceCulture); }
        }

        public static string tmplPlayerStats {
            get { return ResourceManager.GetString("tmplPlayerStats", resourceCulture); }
        }

        public static string tmplPlayerTab {
            get { return ResourceManager.GetString("tmplPlayerTab", resourceCulture); }
        }

        public static string tmplPlayerTabGraph {
            get { return ResourceManager.GetString("tmplPlayerTabGraph", resourceCulture); }
        }

        public static string tmplRotationLegend {
            get { return ResourceManager.GetString("tmplRotationLegend", resourceCulture); }
        }

        public static string tmplSimpleRotation {
            get { return ResourceManager.GetString("tmplSimpleRotation", resourceCulture); }
        }

        public static string tmplStatTables {
            get { return ResourceManager.GetString("tmplStatTables", resourceCulture); }
        }

        public static string tmplSupportTable {
            get { return ResourceManager.GetString("tmplSupportTable", resourceCulture); }
        }

        public static string tmplTargetBuffTab {
            get { return ResourceManager.GetString("tmplTargetBuffTab", resourceCulture); }
        }

        public static string tmplTargetData {
            get { return ResourceManager.GetString("tmplTargetData", resourceCulture); }
        }

        public static string tmplTargetPlayers {
            get { return ResourceManager.GetString("tmplTargetPlayers", resourceCulture); }
        }

        public static string tmplTargets {
            get { return ResourceManager.GetString("tmplTargets", resourceCulture); }
        }

        public static string tmplTargetStats {
            get { return ResourceManager.GetString("tmplTargetStats", resourceCulture); }
        }

        public static string tmplTargetTab {
            get { return ResourceManager.GetString("tmplTargetTab", resourceCulture); }
        }

        public static string tmplTargetTabGraph {
            get { return ResourceManager.GetString("tmplTargetTabGraph", resourceCulture); }
        }

        public static string tmplTargetTabPerPlayerGraph {
            get { return ResourceManager.GetString("tmplTargetTabPerPlayerGraph", resourceCulture); }
        }

    }
}

